### ISSUE TITLE
Figure 1:46.4.2.6.1-1 Should Make the Endpoint Addresses Different

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#43]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:46.4.2.6.1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Figure 1:46.4.2.6.1-1 shows an organization with 2 endpoints, but both endpoints point to the same URL. I think it would make more sense to point them at separate URLs to illustrate why separate endpoints might be required. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Change the endpoints to "https://example.org/xca/query" and "https://example.org/xca/retrieve". 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by jlamy** [comment]
Good point. I agree that the separate URL case is important to show. However, if there are cases where there is the same URL, but you have to model it as separate Endpoints, we should show that.

When I originally did this, the cardinality and binding of connectionType drove us towards that. Now that connectionType is moving to 1..* and example binding, and we'll be able to use it instead of the extension, do we still have a need for multiple Endpoints using the same URL?

**Comment by slagesse-epic** [comment]
I think multiple Endpoints with the same URL should be allowed but not required if connectionType is 1..*. I think if we want to show an example of multiple Endpoints with the same URL, then it would be good to have 2 examples - one where the URLs are the same and one where they are different.

**Comment by jlamy** [comment]
will add another example showing one endpoint
