### ISSUE TITLE
FHIR's Definition of managingOrganization Does Not Match mCSD

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#48]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
1:46.8

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

The use of Endpoint.managingOrganization throughout section 1:46.8 implies that managingOrganization is the Organization that _hosts_ the Endpoint. However, the definition of managingOrganization is:

"The organization that manages this endpoint, even if technically another organization is hosting this in the cloud."

The way this works in practice is that managingOrganization is the Organization that owns the Endpoint Resource and is the Organization that should be contacted first if there are problems, etc. 

In any case, clients shouldn't care who hosts the endpoint, so this detail is not important to be reflected in the directory. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Revise section 1:46.8 to remove the managingOrganization links. 

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by jlamy** [comment]
"clients shouldn't care who hosts the endpoint, so this detail is not important to be reflected in the directory" - agree, and it isn't reflected in the directory. We added the managingOrganization links to the diagrams because they are distinct from hosting and because they are important. In section [1:46.8.1](https://profiles.ihe.net/ITI/mCSD/3.6.1/volume-1.html#14681-endpoint-to-an-organization), we emphasize this distinction: the first three diagrams show the hosting organization (reflected only in the URL) happening to be the same as the managing organization, and the fourth diagram shows how they can be independent. We also preface the diagrams with this: "Note: The managingOrganization of an Endpoint is who users need to contact for support. It may or may not be the same as the organization that hosts it. Since hosting is not reflected in the directory, we are indicating it in the diagrams below by the URLs."

So I think the current content reflects the base FHIR definition exactly; would you agree?

**Comment by slagesse-epic** [comment]
I agree. It seems I missed the note.
