### ISSUE TITLE
Organization.partOf Should Not Imply Technical Connectivity

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.mCSD#49]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:46.8

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Currently, section 1:46.8 is written to imply that of Organization A has Organization.partOf pointed at Organization B and Organization B has endpoints defined, then data held by Organization A can be requested from Organization B, and messages directed to Organization A can be transmitted to Organization B as an intermediary. 

Organization.partOf should be used purely as a means to represent business hierarchies and therefore technical communication between the two Organizations should not be assumed. 

For example, if Organization A were acquired by Organization B, then Organization A is part of B, but they might remain on a separate IT system. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Organization.partOf should not imply technical connectivity. It should be required that technical connectivity, if any such connectivity exists, be represented by a document sharing hierarchy. 

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by jlamy** [comment]
Here's where we agree:
- partOf should not mean "SHALL have connectivity"
- OrgAff with DocShare-federate should mean "SHALL have connectivity"

And here's where we may disagree, but I'm not really sure we do:
- I say partOf should mean "MAY have connectivity".
- You seem to be saying partOf should mean "SHALL NOT have connectivity unless accompanied by an OrgAff with DocShare-federate". 

Because otherwise (i.e. you mean partOf should imply nothing about connectivity) you wouldn't object to this:
- I say a given directory should be able to assert in policy that partOf means "SHALL have connectivity".

I agree that a directory that adopts this policy is making it harder for themselves to transition to a model where business relationships need to be represented without connectivity. I'm just not conditioning their adoption of mCSD on your suggestion.

**Comment by jlamy** [comment]
Committee: connectivity must be conveyed via OrgAff with a code.

**Comment by lukeaduncan** [comment]
Closed because it's in the Open Issue #100
